services:
  - type: web
    name: Rairu-Kun
    runtime: docker
    repo: https://github.com/devculture67/rairu-kun
    region: singapore
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
